repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-yaml
      - id: check-toml
      - id: detect-private-key
      - id: name-tests-test
        args: [ -pytest-test-first ]
      - id: trailing-whitespace
        args: [ --markdown-linebreak-ext=md ]
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: mixed-line-ending
        args: [ --fix=lf ]
      - id: pretty-format-json
        args: [ --autofix ]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.11.0
    hooks:
      # Run the linter. https://docs.astral.sh/ruff/linter/#ruff-check
      - id: ruff
        args: [ --fix ]
      # Run the formatter. https://docs.astral.sh/ruff/formatter/
      - id: ruff-format

  - repo: https://github.com/python-poetry/poetry
    rev: 2.1.1
    # https://python-poetry.org/docs/pre-commit-hooks/
    hooks:
      - id: poetry-check
      - id: poetry-lock
