name: Release Build

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    
    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        version: 2.0.0
    
    - name: Install dependencies
      run: poetry install
    
    - name: Build with PyInstaller
      run: poetry run pyinstaller ./src/run_ui.py --path ./src/ --clean --onefile --noconsole
    
    - name: Rename binary for Windows
      if: matrix.os == 'windows-latest'
      run: mv dist/run_ui.exe dist/rutube_downloader.exe
    
    - name: Rename binary for Unix
      if: matrix.os == 'ubuntu-latest'
      run: mv dist/run_ui dist/rutube_downloader
    
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: binaries-${{ matrix.os }}
        path: dist/rutube_downloader*

  release:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v4
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          binaries-*/rutube_downloader*
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
